### ISSUE TITLE
`mapfile: command not found` under macOS

### ISSUE THREAD

**Issue by pbek** [jitterbit/get-changed-files#15]
Under macOS you will get the error `mapfile: command not found` if you'll try the [CSV example](https://github.com/jitterbit/get-changed-files#get-all-added-and-modified-files-as-csv) to fix the problem with spaces in filenames.

**Comment by pbek** [comment]
The problem is that macOS has bash 3 and `mapfile` was introduced in bash 4.

I found a solution, add this step in front:

```yaml
    - if: contains( matrix.os, 'macos')
      name: Install bash 5.0 under macOS for mapfile
      run: |
        brew install bash
        sudo mv /usr/local/bin/bash /bin/bash
```

`sudo mv /usr/local/bin/bash /bin/bash` is needed because you cannot switch the default shell in a GitHub Workflow and you cannot switch the shell of a step to something else than the predefined shells.
