### ISSUE TITLE
new feature - scan a set of paths

### ISSUE THREAD

**Issue by gabriel-milan** [jitterbit/get-changed-files#39]
Hi there.

Is there a possibility we add support for specific paths scanning?

Example:
```yaml
- id: files
  name: Get modified files
  uses: jitterbit/get-changed-files@v1
  paths:
    - tracked_files/
    - tracked_files_2/
```

IMHO it would be a great feature. Awesome project btw, thank you for sharing!
