### ISSUE TITLE
Error: The head commit for this pull_request event is not ahead of the base commit

### ISSUE THREAD

**Issue by bstuff** [jitterbit/get-changed-files#42]
Error output in GitHub action pushed me to create this issue:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/11030417/132509210-56010815-26a6-4c8e-9e8d-97c9d175126b.png">

./.github/workflows/check-codestyle.yml

```yml
name: Check codestyle

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.number }}/head'

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'

      - name: lint
        run: |
          FILES_COUNT=0
          CHANGED_FILES=""
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
            CHANGED_FILES=$(printf "%s\n${added_modified_file}" "$CHANGED_FILES")
            FILES_COUNT+=1
          done

          set -x
          // truncated due to nda

```
