### ISSUE TITLE
Error: Bad credentials

### ISSUE THREAD

**Issue by dschwarz2011** [jitterbit/get-changed-files#46]
I am receiving a Bad credentials permissions error when trying to run this job. I've tried with both setting the token manually as seen below and without it (which uses the default value specified in action.yml ). Not exactly sure why this is failing as github.token (or GITHUB_TOKEN) is automatically defined when you add the GitHub action. I've checked the permissions in the repo and GITHUB_TOKEN is allowed read write permissions. Any assistance is appreciated.

Below is the workflow playbook.
```
name: Commit

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    types:
      - closed
          
jobs:
  #If Pull request is merged into the master branch
  changedfiles:
    if: github.event.pull_request.merged == true
    runs-on: [ self-hosted ]
    steps:
        - uses: jitterbit/get-changed-files@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            format: 'json'
```
